# Answer 1

In [2]:
import numpy as np

In [ ]:
# Created array :-
a = np.random.randint(1, 100, (3, 3))
a

array([[65, 82, 79],
       [15, 38, 69],
       [74, 33, 44]])

In [ ]:
# Interchange its rows and columns :-

a.T

array([[65, 15, 74],
       [82, 38, 33],
       [79, 69, 44]])

# Answer 2 :-

In [ ]:
#Generate a 1D NumPy array with 10 elements :-

b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape it into a 2x5 array :-

c = b.reshape(2, 5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Again reshape into a 5x2 array :-

c.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Answer 3 :-

In [ ]:
#  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

d = np.random.rand(4, 4)
d

array([[0.84264518, 0.89188873, 0.07601669, 0.55273753],
       [0.56014096, 0.95542873, 0.2916025 , 0.57734243],
       [0.16743977, 0.41853156, 0.92433011, 0.09265339],
       [0.43572911, 0.41496081, 0.25517156, 0.01872291]])

In [ ]:
# Created a 6x6 zeros array.

e = np.zeros((6, 6))
e

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# Adding a border of zeros around it the d :-

e [1:5, 1:5] = d
e

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.84264518, 0.89188873, 0.07601669, 0.55273753,
        0.        ],
       [0.        , 0.56014096, 0.95542873, 0.2916025 , 0.57734243,
        0.        ],
       [0.        , 0.16743977, 0.41853156, 0.92433011, 0.09265339,
        0.        ],
       [0.        , 0.43572911, 0.41496081, 0.25517156, 0.01872291,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

# Answer 4 :-

In [3]:
#  Created an array of integers of (10, 60, 5) from using (start, stop, step) function.

f = np.arange(10, 61, 5)
f

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

# Answer 5 :-

In [ ]:
#  Created a NumPy array of strings ['python', 'numpy', 'pandas'] and stored it in variable array g

g = np.array(['python', 'numpy', 'pandas'])
g



array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
# Uppercase :-

h = np.char.upper(g)
h

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
# Lowercase :-

i = np.char.lower(h)
i

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
# Titlecase

j = np.char.title(i)
j

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
# Capitalize:-

k = np.char.capitalize(j)
k

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

# Answer 6 :-

In [ ]:
# Generate a NumPy array of words. Insert a space between each character of every word in the array.


l = np.array(["Sunita", "is", "studying", "data analytics", "course", "from", "PWskills"])
l

array(['Sunita', 'is', 'studying', 'data analytics', 'course', 'from',
       'PWskills'], dtype='<U14')

In [ ]:
# Insert a space between each character of every word in the array using join function :-

m = np.char.join(" ", l)
m

array(['S u n i t a', 'i s', 's t u d y i n g',
       'd a t a   a n a l y t i c s', 'c o u r s e', 'f r o m',
       'P W s k i l l s'], dtype='<U27')

# Answer 7 :-

In [ ]:
# Created two 2D NumPy arrays and strored in 'o' and 'p' variable arrays :-

o = np.array([[1, 2, 3, 4]])
p = np.array([[5, 6, 7, 8,]])


In [ ]:
o



array([[1, 2, 3, 4]])

In [ ]:
o.ndim

2

In [ ]:
p

array([[5, 6, 7, 8]])

In [ ]:
p.ndim

2

In [ ]:
# Additional :-

o + p

array([[ 6,  8, 10, 12]])

In [ ]:
# Subtraction :-

o - p

array([[-4, -4, -4, -4]])

In [ ]:
# Multiplication :-

o * p

array([[ 5, 12, 21, 32]])

In [ ]:
# Division :-

o / p

array([[0.2       , 0.33333333, 0.42857143, 0.5       ]])

# Answer 8 :-

In [ ]:
# Created a 5x5 identity matrix using eye function :-

q = np.eye(5, 5)
q



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Extracted diagonl value of array 'q' using np.diag() function :-

r = np.diag(q)
r

array([1., 1., 1., 1., 1.])

# Answer 9 :-

In [ ]:
import numpy as np

In [ ]:
s = np.random.randint(0, 1001, 100)
s

array([685, 137, 938, 319, 989, 592, 850, 264, 730, 259, 212, 194, 170,
       460, 891, 181, 584, 647, 322, 143, 635,  11, 146, 735,  54, 818,
       417, 720, 522, 107, 592, 844, 891, 404, 417, 427, 233, 396, 958,
        61, 318, 403, 976, 748, 324, 979, 270, 848, 934, 677, 932, 580,
       176, 952, 235, 924, 326, 780, 958, 352, 475, 630, 650, 645, 658,
       307, 475, 345, 762, 923, 564, 750, 285, 176, 169, 415, 850, 649,
       370, 635, 143, 298, 788, 147, 905, 832, 650, 754, 275, 764, 730,
        54,   8, 936, 216, 359,  68, 438, 618, 312])

In [ ]:
# Generate a NumPy array of 100 random integers between 0 and 1000:-
s = np.random.randint(0, 1001, 100)

# Code to find prime numbers in the array :-
# 2 is the only even prime number
# Even numbers greater than 2 are not prime

prime_numbers = [num for num in s if is_prime(num)]

def is_prime(num):

    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    i = 3
    while i * i <= num:
        if num % i == 0:
            return False
        i += 2
    return True


print(s)
print(prime_numbers)


[554 973 368 999 917 201 383 512 906 370 555 954 383  23 699 130 377  98
 574 931 734 123 963 594 942 739 148 209 562 411 782  41  58 705  36 778
  86  43 872  11 770 307  80  32 182 128 806 275 174 554 371 184 444 488
 589 286 280 637 770 515  94 226 875 269 880 296 328  19 607 840 410 450
 248 180 323 829 782 864 260 963 749 139 598 461 889 621 843 696 528 152
 925 149 110  25 464 956 889 886 117 445]
[383, 383, 23, 739, 41, 43, 11, 307, 269, 19, 607, 829, 139, 461, 149]


# Answer 10 :-

In [ ]:
# Lets take daily_temperatures = 13 and 40 in Celsius.
# Days in a month = 30 days


daily_temp = np.random.randint(13, 40, 30)

# Reshape the array into 5 weeks and each week has 7 days with length and reshape function
num_weeks = len(daily_temp) // 7
weekly_temp = daily_temp[ :num_weeks * 7].reshape(num_weeks, 7)

weekly_averages = np.mean(weekly_temp, axis=1)

print(daily_temp)
print(weekly_averages)


[34 27 32 29 31 21 23 39 25 39 21 39 26 29 30 18 36 21 37 39 15 26 22 28
 19 28 30 27 13 26]
[28.14285714 31.14285714 28.         25.71428571]
